src/fbfeeds/fbfeeds/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^shoutout/', include('feeds.urls', namespace='feeds')),
    url(r'^admin/', include(admin.site.urls)),
)

src/fbfeeds/feeds/urls.py
from django.contrib import messages
from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required

from feeds.forms import LoginForm, SignupForm
from feeds import views

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^feeds/$', views.FeedsView.as_view(), name='feeds'),
    url(r'^login/$', 'django.contrib.auth.views.login', {
        'template_name': 'feeds/index.html',
        'extra_context': {
            'signup_form': SignupForm(),
            'login_form': LoginForm(),
        },
    }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/shoutout'}, name='logout'),
    url(r'^(?P<post_id>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<post_id>\d+)/like/$',
        views.LikeRedirectView.as_view(), name='like'),
    url(r'^(?P<post_id>\d+)/unlike/$',
        views.UnlikeRedirectView.as_view(), name='unlike'),
    url(r'^comment/$', views.CommentRedirectView.as_view(), name='comment'),
    url(r'^(?P<post_id>\d+)/edit_post/$',
        views.EditPostRedirectView.as_view(), name='edit_post'),
    url(r'^(?P<post_id>\d+)/delete_post/$',
        views.DeletePostRedirectView.as_view(), name='delete_post'),
    url(r'^profile/(?P<slug>\w+)/$',
        views.ProfileView.as_view(), name='profile'),
    url(r'^profile_edit/$', views.ProfileEditView.as_view(),
        name='edit_profile_view'),
    url(r'^edit_profile/$', views.EditProfileRedirectView.as_view(),
        name='edit_profile'),
    url(r'^post/$', views.PostRedirectView.as_view(), name='post'),
    url(r'^create_user/$', views.CreateUserRedirectView.as_view(),
        name='create_user'),
)

src/fbfeeds/feeds/models.py
from django.db import models
from django.contrib.auth.models import User

from fbfeeds import settings


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    gender = models.CharField(
        blank=True, max_length=1, choices=(('F', 'Female'), ('M', 'Male'),))
    prof_pic = models.ImageField(null=True, upload_to='feeds/prof_pics/')
    birthdate = models.DateField(null=True)
    bio = models.TextField(blank=True)

    def __unicode__(self):
        return self.user.username


class Post(models.Model):
    content = models.TextField()
    author = models.ForeignKey(Profile)
    post_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.content

    def to_dict(self):
        return {
            'content': self.content,
            'author': author,
        }


class Like(models.Model):
    post = models.ForeignKey(Post)
    liker = models.ForeignKey(Profile)
    like_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return repr(self.id)


class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post)
    author = models.ForeignKey(Profile)
    comment_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.content

src/fbfeeds/feeds/forms.py
from django.contrib.auth import forms as user_forms
from django.contrib.auth.models import User

from feeds.models import Post, Comment, Profile
from django import forms


class LoginForm(user_forms.AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter username...',
        'required': True,
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter password...',
        'required': True,
    }))

    class Meta:
        model = User
        fields = ['username', 'password']


class SignupForm(user_forms.UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter username...',
        'required': True,
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter password...',
        'required': True,
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm password...',
        'required': True,
    }))

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'placeholder': 'Enter email...',
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'placeholder': 'Enter first name...',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'placeholder': 'Enter last name...',
                }
            )
        }


class UserEditForm(user_forms.UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'disabled': True,
    }))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'placeholder': 'Enter email...',
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'placeholder': 'Enter first name...',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'placeholder': 'Enter last name...',
                }
            )
        }


class ProfileEditForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['birthdate', 'bio', 'prof_pic', 'gender']
        widgets = {
            'user_id': forms.HiddenInput(),
            'birthdate': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'yyyy-mm-dd',
                }
            ),
            'bio': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Let your fans know about yourself...',
                    'rows': 3,
                }
            ),
            'prof_pic': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'gender': forms.RadioSelect(),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content', 'post', 'author']
        widgets = {
            'post': forms.HiddenInput(),
            'author': forms.HiddenInput(),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'style': 'width: 600px',
                    'placeholder': 'What do you think...?',
                    'required': True,
                    'rows': 2,
                }
            )
        }


class ShoutoutForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['content', 'author']
        widgets = {
            'author': forms.HiddenInput(),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'placeholder': 'Blurt out your thoughts...',
                    'required': True,
                    'rows': 7,
                }
            ),
        }

src/fbfeeds/feeds/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, RedirectView

from feeds.models import Post, Like, Comment, Profile
from feeds import forms


class LoginRequiredMixin(object):

    @method_decorator(login_required)
    def dispath(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class IndexView(TemplateView):
    template_name = 'feeds/index.html'

    def get(self, request):
        if not request.user.is_authenticated():
            return self.render_to_response({
                'signup_form': forms.SignupForm(),
                'login_form': forms.LoginForm(),
            })
        else:
            return redirect(reverse('feeds:feeds'))


class FeedsView(LoginRequiredMixin, TemplateView):
    template_name = 'feeds/feeds.html'

    def get_context_data(self, *args, **kwargs):
        context = super(FeedsView, self).get_context_data(*args, **kwargs)
        context.update({
            'latest_posts': Post.objects.all().order_by('-post_date')[:10],
            'session_user': self.request.user.profile,
            'shoutout_form': forms.ShoutoutForm(initial={
                'author': self.request.user.profile,
            }),
            'is_more_than_10': False,
        })
        return context


class ProfileView(TemplateView):
    template_name = 'feeds/profile.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileView, self).get_context_data(*args, **kwargs)
        profile = get_object_or_404(Profile, user__username=kwargs['slug'])
        latest_posts = Post.objects.filter(
            author=profile).order_by('-post_date')[:10]
        context.update({
            'profile': profile,
            'latest_posts': latest_posts,
            'shoutout_form': forms.ShoutoutForm(initial={
                'author': self.request.user.profile,
            }),
            'session_user': self.request.user.profile
        })
        return context


class ProfileEditView(TemplateView):
    template_name = 'feeds/edit_profile.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileEditView, self).get_context_data(
            *args, **kwargs)
        context.update({
            'session_user': self.request.user.profile,
            'shoutout_form': forms.ShoutoutForm(initial={
                'author': self.request.user.profile,
            }),
            'user_edit_form': forms.UserEditForm(instance=self.request.user),
            'profile_edit_form': forms.ProfileEditForm(
                instance=self.request.user.profile, initial={
                    'user_id': self.request.user.profile.pk}),
        })
        return context


class DetailView(TemplateView):
    template_name = 'feeds/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DetailView, self).get_context_data(*args, **kwargs)
        post = get_object_or_404(Post, pk=kwargs['post_id'])
        likers = Like.objects.filter(post=post).order_by('-like_date')
        comments = post.comment_set.order_by('-comment_date')
        context.update({
            'post': post,
            'session_user': self.request.user.profile,
            'shoutout_form': forms.ShoutoutForm(initial={
                'author': self.request.user.profile,
            }),
            'comment_form': forms.CommentForm(initial={
                'author': self.request.user.profile,
                'post': post,
            }),
            'has_liked': bool(likers.filter(liker=self.request.user.profile)),
            'comments': comments,
        })
        return context


class CreateUserRedirectView(RedirectView):

    def post(self, request):
        signup_form = forms.SignupForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            print user
            session_user = authenticate(
                username=request.POST['username'],
                password=request.POST['password1']
            )
            if session_user:
                if session_user.is_active():
                    login(request, session_user)
                    return redirect(reverse('feeds:edit_profile_view'))
                else:
                    messages.error(request, 'It was a disabled account.')
                    return redirect(reverse('feeds:index'))
            else:
                messages.error(request, 'Invalid login.')
                return redirect(reverse('feeds:index'))
        else:
            messages.error(request, 'Please input valid data accordingly.')
            return redirect(reverse('feeds:index'))


class PostRedirectView(RedirectView):

    def get(self, request):
        form = forms.ShoutoutForm(request.POST)
        print form.is_valid()
        if form.is_valid():
            post = form.save()
            messages.success(request, 'You posted a shoutout successfully.')
            return redirect(reverse('feeds:detail', args=(post.id,)))
        else:
            messages.error(request, 'It was an invalid post.')
            return redirect(reverse('feeds:feeds'))


class EditPostRedirectView(RedirectView):

    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        post.content = request.POST['content']
        post.save()
        messages.success(request, 'You modified this post.')
        return redirect(reverse('feeds:detail', args=(post_id,)))


class DeletePostRedirectView(RedirectView):

    def get(get, request, post_id):
        Post.objects.get(pk=post_id).delete()
        messages.success(request, 'You deleted a shoutout.')
        return redirect(reverse('feeds:feeds'))


class EditProfileRedirectView(RedirectView):

    def get(self, request):
        password = None
        if not request.user.is_anonymous():
            password = request.user.password
        user_form = forms.UserEditForm(
            request.POST, instance=request.user,
            initial={'password': password})
        profile_form = forms.ProfileEditForm(request.POST, request.FILES,
                                             instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully.')
        else:
            messages.error(request, 'Invalid login.')
        return redirect(reverse(
            'feeds:profile', args=(request.user.username,)))


class LikeRedirectView(RedirectView):

    def get(self, request, post_id):
        like = Like.objects.create(
            post=get_object_or_404(Post, pk=post_id),
            liker=request.user.profile,
        )
        return redirect(reverse('feeds:detail', args=(post_id,)))


class UnlikeRedirectView(RedirectView):

    def get(self, request, post_id):
        Like.objects.filter(
            post=get_or_create(Post, pk=post_id),
            liker=request.user.profile,
        ).delete()
        return redirect(reverse('feeds:detail', args=(post_id,)))


class CommentRedirectView(RedirectView):

    def get(self, request):
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(reverse('feeds:detail', args=(request.POST['post'],)))

src/fbfeeds/feeds/templates/feeds/detail.html
<!DOCTYPE html>
<html lang="en">
{% include 'static/head.html' %}

<body>
	{% include 'static/header.html' %}

	<div class="container std-container">
		<h3>
			<span class="glyphicon glyphicon-bullhorn"></span>
			<a href="{% url 'feeds:profile' post.author.user.username %}">@{{ post.author.user.username }}</a> shouted out:
		</h3>		
		<div class="pull-right user-buttons">
			<div class="btn-group" role="group">
			{% if has_liked %}
				<a class="btn btn-success" href="{% url 'feeds:unlike' post.id %}">
					<span class="glyphicon glyphicon-heart"></span>
				</a>
			{% else %}
				<a class="btn btn-primary" href="{% url 'feeds:like' post.id %}">
					<span class="glyphicon glyphicon-heart"></span>
				</a>
			{% endif %}
			{% if post.author.user.pk == session_user.user.pk %}
				<button type="button" class="btn btn-warning" data-toggle="modal" data-target=".edit-post">
					<span class="glyphicon glyphicon-pencil"></span>
				</button>
				<button type="button" class="btn btn-danger" data-toggle="modal" data-target=".delete-post">
					<span class="glyphicon glyphicon-trash"></span>
				</button>
			{% endif %}
			{% if post.like_set.count > 0 %}
				<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".show-likers">
					Likers <span class="badge">{{ post.like_set.count }}</span>
				</button>
			{% endif %}
			</div>
			<div class="modal fade edit-post" tabindex="-1" role="dialog">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span>&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Edit post</h4>
						</div>
						<form action="{% url 'feeds:edit_post' post.id %}" method="post">
						{% csrf_token %}
							<div class="modal-body">
								<div class="form-group">
									<textarea name="content" rows="4" class="form-control">{{ post.content }}</textarea>
								</div>
							</div>
							<div class="modal-footer">
								<button type="submit" class="btn btn-primary">Save changes</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			<div class="modal fade delete-post" tabindex="-1" role="dialog">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span>&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Are you sure you really want to delete this post?</h4>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
							<a href="{% url 'feeds:delete_post' post.id %}" class="btn btn-danger">Delete</a>
						</div>
					</div>
				</div>
			</div>
			<div class="modal fade show-likers" tabindex="-1" role="dialog">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span>&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Likers of this post</h4>
						</div>
						<div class="modal-body">
							<ul class="list-group">
							{% for like in post.like_set.all %}
								<li class="list-group-item">
									<span class="glyphicon glyphicon-user"></span>
									<a href="{% url 'feeds:profile' like.liker.user.username %}">@{{ like.liker.user.username }}</a> on 
									<em>{{ like.like_date }}</em>
								</li>
							{% endfor %}
							</ul>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					</div>
				</div>
			</div>
		</div>
		<blockquote class="well">
			<p><em>{{ post.content|linebreaks }}</em></p>
			<footer>on <em>{{ post.post_date }}</em></footer>
		</blockquote>
		{% include 'static/errorflash.html' %}
		<div class="well">
			<ul class="list-group">
				{% for comment in comments %}
					<li class="list-group-item">
						<span class="glyphicon glyphicon-comment"></span>
						<a href="{% url 'feeds:profile' comment.author.user.username %}">@{{ comment.author }}</a>: 
						<em>{{ comment.content }}</em>
					</li>
				{% empty %}
					<p>Be the first to comment!</p>
				{% endfor %}
				<li class="list-group-item">
					<form action="{% url 'feeds:comment' %}" method="post" class="form-inline">
					{% csrf_token %}
						{{ comment_form.post }}
						{{ comment_form.author }}
						{{ comment_form.content }}
						<button type="submit" class="btn btn-primary btn-sm" style="margin-left: 4px">
							<span class="glyphicon glyphicon-bullhorn"></span> Comment
						</button>
					</form>
				</li>
			</ul>
		</div>
	</div>

	{% include 'static/footer.html' %}
	{% include 'static/scripts.html' %}
</body>

</html>

src/fbfeeds/feeds/templates/feeds/edit_profile.html
<!DOCTYPE html>
<html lang="en">
{% include 'static/head.html' %}

<body>
	{% include 'static/header.html' %}

	<div class="container std-container">
		<h4>Edit profile</h4>
		{% include 'static/errorflash.html' %}
		<form action="{% url 'feeds:edit_profile' %}" method="post" class="form-horizontal" enctype="multipart/form-data">
		{% csrf_token %}
			{{ profile_edit_form.user_id }}
			<div class="form-group">
				<label for="username" class="col-sm-3 control-label">Username</label>
				<div class="col-sm-9">
					{{ user_edit_form.username }}
				</div>
			</div>
			<div class="form-group">
				<label for="firstname" class="col-sm-3 control-label">First Name</label>
				<div class="col-sm-9">
					{{ user_edit_form.first_name }}
				</div>
			</div>
			<div class="form-group">
				<label for="lastname" class="col-sm-3 control-label">Last Name</label>
				<div class="col-sm-9">
					{{ user_edit_form.last_name }}
				</div>
			</div>
			<div class="form-group">
				<label for="email" class="col-sm-3 control-label">Email Address</label>
				<div class="col-sm-9">
					{{ user_edit_form.email }}
				</div>
			</div>
			<div class="form-group">
				<label for="birthdate" class="col-sm-3 control-label">Birthdate</label>
				<div class="col-sm-9">
					{{ profile_edit_form.birthdate }}
				</div>
			</div>
			<div class="form-group">
				<label for="bio" class="col-sm-3 control-label">Bio (Description)</label>
				<div class="col-sm-9">
					{{ profile_edit_form.bio }}
				</div>
			</div>
			<div class="form-group">
				<label for="prof_pic" class="col-sm-3 control-label">Profile Picture</label>
				<div class="col-sm-9">
					{{ profile_edit_form.prof_pic }}
				</div>
			</div>
			<div class="form-group">
				<label for="gender" class="col-sm-3 control-label">Gender</label>
				<div class="col-sm-9">
					<div class="radio">
						{{ profile_edit_form.gender }}
					</div>
				</div>
			</div>
			<button type="submit" class="btn btn-primary pull-right">Submit</button>
		</form>
	</div>

	{% include 'static/footer.html' %}
	{% include 'static/scripts.html' %}
</body>

</html>

src/fbfeeds/feeds/templates/feeds/feeds.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
{% include 'static/head.html' %}

<body>
	{% include 'static/header.html' %}

	<div class="container std-container">
		<div class="row">
			<div class="col-md-4">
				<h2>Hello, <a href="{% url 'feeds:profile' session_user.user.username %}"><em>@{{ session_user.user.username }}</em></a>!</h2>
				<div>
					<form action="{% url 'feeds:post' %}" method="post">
					{% csrf_token %}
						<div class="form-group">
							{{ shoutout_form.content }}
						</div>
						{{ shoutout_form.author }}
						<button type="submit" class="btn btn-primary btn-sm">
							<span class="glyphicon glyphicon-pencil"></span> Shout Out!
						</button>
					</form>
				</div>
			</div>
			<div class="col-md-8">
			{% include 'static/errorflash.html' %}
			{% include 'static/postwall.html' %}
			</div>
		</div>
	</div>

	{% include 'static/footer.html' %}
	{% include 'static/scripts.html' %}
</body>

</html>

src/fbfeeds/feeds/templates/feeds/index.html
{% include 'static/head.html' %}

<body>
	<div class="container std-container">
		<div class="page-header">
			<h1><span class="brand">ShoutOut</span> <small><em>| The New Microblogger</em></small></h1>
		</div>
		<div style="width: 30%; margin: 0 auto">
			<form action="{% url 'feeds:login' %}" method="post">
			{% csrf_token %}
				<div class="form-group">
					<label for="username">Username</label>
					{{ login_form.username }}
				</div>
				<div class="form-group">
					<label for="password">Password</label>
					{{ login_form.password }}
				</div>
				<button type="submit" class="btn btn-primary">Sign in</button>
			</form>
			<p>Doesn't have an account yet?</p>
			<button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target=".signup">
				<span class="glyphicon glyphicon-pencil"></span> Be a Shouter!
			</button>
			<div class="modal fade signup" tabindex="-1" role="dialog">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span>&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Account Registration</h4>
						</div>
						<form action="{% url 'feeds:create_user' %}" method="post" class="form-horizontal">
						{% csrf_token %}
							<div class="modal-body">
								<div class="form-group">
									<label for="username" class="col-sm-3 control-label">Username</label>
									<div class="col-sm-9">
										{{ signup_form.username }}
									</div>
								</div>
								<div class="form-group">
									<label for="firstname" class="col-sm-3 control-label">First Name</label>
									<div class="col-sm-9">
										{{ signup_form.first_name }}
									</div>
								</div>
								<div class="form-group">
									<label for="lastname" class="col-sm-3 control-label">Last Name</label>
									<div class="col-sm-9">
										{{ signup_form.last_name }}
									</div>
								</div>
								<div class="form-group">
									<label for="email" class="col-sm-3 control-label">Email Address</label>
									<div class="col-sm-9">
										{{ signup_form.email }}
									</div>
								</div>
								<div class="form-group">
									<label for="password" class="col-sm-3 control-label">Password</label>
									<div class="col-sm-9">
										{{ signup_form.password1 }}
									</div>
								</div>
								<div class="form-group">
									<label for="conf_pass" class="col-sm-3 control-label">Confirm Password</label>
									<div class="col-sm-9">
										{{ signup_form.password2 }}
									</div>
								</div>
							</div>
							<div class="modal-footer">
								<button type="submit" class="btn btn-primary pull-right">Go to Hell!</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			
			{% include 'static/errorflash.html' %}
		</div>
	</div>
	
	{% include 'static/scripts.html' %}
</body>

</html>

src/fbfeeds/feeds/templates/feeds/profile.html
<!DOCTYPE html>
<html lang="en">
{% include 'static/head.html' %}

<body>
	{% include 'static/header.html' %}

	<div class="container std-container">
		<div class="page-header">
			<h1>@{{ profile.user.username }} | <small><em>{{ profile.user.first_name }} {{ profile.user.last_name }}</em></small></h1>
		</div>
		<ul class="list-group">
			{% include 'static/errorflash.html' %}
			{% include 'static/postwall.html' %}
		</ul>
	</div>
	
	{% include 'static/footer.html' %}
	{% include 'static/scripts.html' %}
</body>

</html>